- id: "baidu"
  name: "百度一下"
  placeholder: "百度一下，你就知道"
  color: "#0c498c"
  url: "https://www.baidu.com/s?word="
- id: "wuzhui"
  name: "无追搜索"
  placeholder: "隐私保护，化繁为简"
  color: "#19DBF7"
  url: "https://www.wuzhuiso.com/s?q="
- id: "bing"
  name: "Bing必应"
  placeholder: "微软必应搜索"
  color: "#696a6d"
  url: "https://cn.bing.com/search?q="
- id: "DuckDuckGo"
  name: "DuckDuckGo"
  placeholder: "开启不受网络跟踪的搜索之旅"
  color: "#DE5833"
  url: "https://duckduckgo.com/?q="
- id: "github"
  name: "Github"
  placeholder: "请输入搜索的项目"
  color: "#000000"
  url: "https://github.com/search?q="
- id: "google"
  name: "谷歌搜索"
  placeholder: "值得信任的搜索引擎"
  color: "#3B83FA"
  url: "https://www.google.com/search?hl=zh-CN&q="
- id: "Linux 命令"
  name: "Linux 命令"
  placeholder: "Linux 命令搜索"
  color: "#696a6d"
  url: "https://linux.lylme.com/list.html#!kw="
- id: "fanyi"
  name: "百度翻译"
  placeholder: "输入翻译内容（自动检测语言）"
  color: "#0084fe"
  url: "https://fanyi.baidu.com/#auto/zh/"
- id: "google-translate"
  name: "Google翻译"
  placeholder: "输入翻译内容 (自动检测语言)"
  color: "#696a6d"
  url: "https://translate.google.com/?sl=auto&tl=zh-CN&text="
- id: "iconfont"
  name: "iconfont"
  placeholder: "搜索图标"
  color: "#696a6d"
  url: "https://www.iconfont.cn/search/index?searchType=icon&q="
- id: "Crxsousou"
  name: "Crx搜搜"
  placeholder: "输入你想搜索的chrome浏览器插件"
  color: "#696a6d"
  url: "https://www.crxsoso.com/search?store=chrome&keyword="
- id: "metaso"
  name: "秘塔AI搜索"
  placeholder: "没有广告，直达结果"
  color: "#0084fe"
  url: "https://metaso.cn/?q="